version: '3.8'
services:
  postgres:
    image: 'postgres:14.0'
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=91696192##
      - POSTGRES_DB=gvendas
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'